
# The pre-processor and compiler options.
MY_CFLAGS := 

# The linker options.
# libraries
MY_LIBS += -lboost_program_options -lpthread -lconfig++ 

# The pre-processor options used by the cpp (man cpp for more).
#CPPFLAGS := -std=c++11 -O3 -pedantic -pedantic-errors -Wall -Wextra
#CXXFLAGS := -std=c++11 -O3 -pedantic -pedantic-errors -Wall -Wextra


# The options used in linking as well as in any direct use of ld.
LDFLAGS :=


# source directories
SRCDIRS += src
SRCDIRS += src/interface
SRCDIRS += src/server

# The executable file name.
# If not specified, current directory name or `a.out' will be used.
PROGRAM := videocit_entrance

# load common definitions to all makefile
include standard.mk
